In [14]:
%matplotlib inline
from tools import *

# Ch04 数据表示与特征工程

-   连续特征 ( Continuous Feature ) 。
-   分类特征 ( Categorical Feature ) ，也叫离散特征 ( Discrete Feature ) 。

特征工程：找到最佳的数据表示。

虽然神经网络已经可以自动完成特征的选择和变换，但是深入学习特征变换的原理，可以帮助理解神经网络对数据进行了哪种变化，从而加深对数据的理解，能够更加显式地操纵数据变换过程，提高数据变换的效率和加入更多的先验信息。

## 4.1 分类变量

### 4.1.1 One-Hot 编码 ( 虚拟变量 )

One-Hot 编码，也叫 N 取一编码 ( one-out-of-N encoding ) ，也叫虚拟变量 ( dummy variable ) 。

虚拟变量的思想：将一个分类变量替换为一个或者多个新的特征，新特征取值为0或者1。

In [6]:
import os
# The file has no headers naming the columns, so we pass header=None
# and provide the column names explicitly in "names"
# adult.data 中没有 header，因此 header=None，使用 names 显式提供数据列的名称
adult_path = os.path.join(mglearn.datasets.DATA_PATH, "adult.data")
data = pd.read_csv(
    adult_path, header=None, index_col=False,
    names=['age', 'workclass', 'fnlwgt', 'education',  'education-num',
           'marital-status', 'occupation', 'relationship', 'race', 'gender',
           'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
           'income'])
# For illustration purposes, we only select some of the columns
data = data[['age', 'workclass', 'education', 'gender', 'hours-per-week',
             'occupation', 'income']]
# IPython.display allows nice output formatting within the Jupyter notebook
display(data.head())

age          workclass   education   gender  hours-per-week          occupation  income
0   39          State-gov   Bachelors     Male              40        Adm-clerical   <=50K
1   50   Self-emp-not-inc   Bachelors     Male              13     Exec-managerial   <=50K
2   38            Private     HS-grad     Male              40   Handlers-cleaners   <=50K
3   53            Private        11th     Male              40   Handlers-cleaners   <=50K
4   28            Private   Bachelors   Female              40      Prof-specialty   <=50K

#### 1. 检查字符串编码的分类数据

In [9]:
print(data.gender.value_counts())

 Male      21790
 Female    10771
Name: gender, dtype: int64


In [10]:
print("原始特征的名称:\n", list(data.columns), "\n")
data_dummies = pd.get_dummies(data)
print("扩展后的所有特征名称:\n", list(data_dummies.columns))

原始特征的名称:
 ['age', 'workclass', 'education', 'gender', 'hours-per-week', 'occupation', 'income'] 

扩展后的所有特征名称:
 ['age', 'hours-per-week', 'workclass_ ?', 'workclass_ Federal-gov', 'workclass_ Local-gov', 'workclass_ Never-worked', 'workclass_ Private', 'workclass_ Self-emp-inc', 'workclass_ Self-emp-not-inc', 'workclass_ State-gov', 'workclass_ Without-pay', 'education_ 10th', 'education_ 11th', 'education_ 12th', 'education_ 1st-4th', 'education_ 5th-6th', 'education_ 7th-8th', 'education_ 9th', 'education_ Assoc-acdm', 'education_ Assoc-voc', 'education_ Bachelors', 'education_ Doctorate', 'education_ HS-grad', 'education_ Masters', 'education_ Preschool', 'education_ Prof-school', 'education_ Some-college', 'gender_ Female', 'gender_ Male', 'occupation_ ?', 'occupation_ Adm-clerical', 'occupation_ Armed-Forces', 'occupation_ Craft-repair', 'occupation_ Exec-managerial', 'occupation_ Farming-fishing', 'occupation_ Handlers-cleaners', 'occupation_ Machine-op-inspct', 'occupation_ Other

In [11]:
display(data_dummies.head())

age  hours-per-week  workclass_ ?  workclass_ Federal-gov  workclass_ Local-gov  workclass_ Never-worked  workclass_ Private  workclass_ Self-emp-inc  workclass_ Self-emp-not-inc  workclass_ State-gov  workclass_ Without-pay  education_ 10th  education_ 11th  education_ 12th  education_ 1st-4th  education_ 5th-6th  education_ 7th-8th  education_ 9th  education_ Assoc-acdm  education_ Assoc-voc  education_ Bachelors  education_ Doctorate  education_ HS-grad  education_ Masters  education_ Preschool  education_ Prof-school  education_ Some-college  gender_ Female  gender_ Male  occupation_ ?  occupation_ Adm-clerical  occupation_ Armed-Forces  occupation_ Craft-repair  occupation_ Exec-managerial  occupation_ Farming-fishing  occupation_ Handlers-cleaners  occupation_ Machine-op-inspct  occupation_ Other-service  occupation_ Priv-house-serv  occupation_ Prof-specialty  occupation_ Protective-serv  occupation_ Sales  occupation_ Tech-support  occupation_ Transport-moving  \
0   39              40             0                       0                     0                        0                   0                        0                            0                     1                       0                0                0                0                   0                   0                   0               0                      0                     0                     1                     0                   0                   0                     0                       0                        0               0             1              0                         1                         0                         0                            0                            0                              0                              0                          0                            0                           0                            0                  0                         0                             0   
1   50              13             0                       0                     0                        0                   0                        0                            1                     0                       0                0                0                0                   0                   0                   0               0                      0                     0                     1                     0                   0                   0                     0                       0                        0               0             1              0                         0                         0                         0                            1                            0                              0                              0                          0                            0                           0                            0                  0                         0                             0   
2   38              40             0                       0                     0                        0                   1                        0                            0                     0                       0                0                0                0                   0                   0                   0               0                      0                     0                     0                     0                   1                   0                     0                       0                        0               0             1              0                         0                         0                         0                            0                            0                              1                              0                          0                            0                           0                            0                  0                         0                             0   
3   53              40             0           

In [19]:
show_title("提取包含特征的列")
features = data_dummies.loc[:, 'age':'occupation_ Transport-moving']
# Extract NumPy arrays
X = features.values
y = data_dummies['income_ >50K'].values
print("X.shape: {}  y.shape: {}".format(X.shape, y.shape))
print("X=")
display(X[:5])
print("y=",y[:5])
bin_count = np.bincount(y)
print('np.bin_count(y) = (0的个数 {}) 和 (1的个数 {})'.format(bin_count[0], bin_count[1]))

=============== >提取包含特征的列< ===============
X.shape: (32561, 44)  y.shape: (32561,)
X=


array([[39, 40,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  1,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [50, 13,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [38, 40,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0],
       [53, 40,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0],
       [28, 40,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0]], dtype=int64)

y= [0 0 0 0 0]
np.bin_count(y) = (0的个数 24720) 和 (1的个数 7841)


In [20]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
logreg = LogisticRegression()
logreg.fit(X_train, y_train)
print("Test score: {:.2f}".format(logreg.score(X_test, y_test)))

Test score: 0.81


### 4.1.2. 数字可以编码分类变量

In [21]:
# create a DataFrame with an integer feature and a categorical string feature
# 创建 pandas 的 DataFrame
# 一个整型特征，一个分类字符串特征
demo_df = pd.DataFrame({'Integer Feature': [0, 1, 2, 1],
                        'Categorical Feature': ['socks', 'fox', 'socks', 'box']})
show_title("表4-4：包含分类字符串特征和整数特征的数据框")
display(demo_df)

=============== >表4-4：包含分类字符串特征和整数特征的数据框< ===============


Integer Feature Categorical Feature
0                0               socks
1                1                 fox
2                2               socks
3                1                 box

In [22]:
show_title("表4-5：表4-4中数据的One-Hot编码版本，整数特征不变")
display(pd.get_dummies(demo_df))

=============== >表4-4-str：包含分类字符串特征和整数字符串特征的数据框< ===============


Integer Feature  Categorical Feature_box  Categorical Feature_fox  Categorical Feature_socks
0                0                        0                        0                          1
1                1                        0                        1                          0
2                2                        0                        0                          1
3                1                        1                        0                          0

In [23]:
show_title("表4-5：表4-4-str中数据的One-Hot编码版本，整数字符串特征也同时编码")
demo_df['Integer Feature'] = demo_df['Integer Feature'].astype(str)
display(pd.get_dummies(demo_df, columns=['Integer Feature', 'Categorical Feature']))

=============== >表4-5：表4-4中数据的One-Hot编码版本，整数特征不变< ===============


Integer Feature_0  Integer Feature_1  Integer Feature_2  Categorical Feature_box  Categorical Feature_fox  Categorical Feature_socks
0                  1                  0                  0                        0                        0                          1
1                  0                  1                  0                        0                        1                          0
2                  0                  0                  1                        0                        0                          1
3                  0                  1                  0                        1                        0                          0

## 使用 Scikit-Learn 进行 OneHot编码 和 列转换

In [27]:
from sklearn.preprocessing import OneHotEncoder
# Setting sparse=False means OneHotEncode will return a numpy array, not a sparse matrix
# 使用 sparse=False 避免返回稀疏矩阵，而是返回 numpy 数组
ohe = OneHotEncoder(sparse=False)
print(ohe.fit_transform(demo_df))

[[1. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1.]
 [0. 1. 0. 1. 0. 0.]]


In [28]:
print(ohe.get_feature_names())

['x0_0' 'x0_1' 'x0_2' 'x1_box' 'x1_fox' 'x1_socks']


In [36]:
display(data.head())

age          workclass   education   gender  hours-per-week          occupation  income
0   39          State-gov   Bachelors     Male              40        Adm-clerical   <=50K
1   50   Self-emp-not-inc   Bachelors     Male              13     Exec-managerial   <=50K
2   38            Private     HS-grad     Male              40   Handlers-cleaners   <=50K
3   53            Private        11th     Male              40   Handlers-cleaners   <=50K
4   28            Private   Bachelors   Female              40      Prof-specialty   <=50K

In [40]:
show_title("不同类别的类别数目，共计 42 个")
print("workclass 的类别数目 = ", np.unique(data['workclass']).size)
print("education 的类别数目 = ", np.unique(data['education']).size)
print("gender 的类别数目 = ", np.unique(data['gender']).size)
print("occupation 的类别数目 = ", np.unique(data['occupation']).size)

=============== >不同类别的类别数目，共计 42 个< ===============
workclass 的类别数目 =  9
education 的类别数目 =  16
gender 的类别数目 =  2
occupation 的类别数目 =  15


In [41]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler

ct = ColumnTransformer(
    [("scaling", StandardScaler(), ['age', 'hours-per-week']),
     ("onehot", OneHotEncoder(sparse=False), ['workclass', 'education', 'gender', 'occupation'])])

In [42]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
# get all columns apart from income for the features
data_features = data.drop("income", axis=1)
# split dataframe and income
X_train, X_test, y_train, y_test = train_test_split(
    data_features, data.income, random_state=0)

ct.fit(X_train)
X_train_trans = ct.transform(X_train)

In [43]:
print(X_train.shape)
display(X_train[:3])

(24420, 6)


age workclass education   gender  hours-per-week         occupation
26464   59   Private      12th     Male              35   Transport-moving
16134   71   Private   Masters   Female              20      Other-service
4747    42   Private   Masters     Male              40     Prof-specialty

In [44]:
print(X_train_trans.shape)
display(X_train_trans[:3])

(24420, 44)


array([[ 1.499, -0.445,  0.   ,  0.   ,  0.   ,  0.   ,  1.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  1.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  1.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  1.   ],
       [ 2.38 , -1.668,  0.   ,  0.   ,  0.   ,  0.   ,  1.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         1.   ,  0.   ,  0.   ,  0.   ,  1.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  1.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ],
       [ 0.25 , -0.037,  0.   ,  0.   ,  0.   ,  0.   ,  1.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         1.   ,  0.   ,  0.   ,  0.   ,  0.   ,  1.   ,  0.   ,  0.   

In [45]:
logreg = LogisticRegression(max_iter=1000)
logreg.fit(X_train_trans, y_train)

X_test_trans = ct.transform(X_test)
print("Test score: {:.2f}".format(logreg.score(X_test_trans, y_test)))

Test score: 0.81


In [46]:
ct.named_transformers_.onehot

OneHotEncoder(sparse=False)

### 更加简洁的列转换函数 ``make_columntransformer()``

In [47]:
from sklearn.compose import make_column_transformer
ct = make_column_transformer(
    (StandardScaler(),['age', 'hours-per-week']),
    (OneHotEncoder(sparse=False),['workclass', 'education', 'gender', 'occupation']))